'use client'

import { usePathname } from 'next/navigation'
import localFont from "next/font/local";
import AdminLayout from "../components/adminDashboard/AdminLayout";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "QUEST ERP",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname()

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {pathname == "/" ? (
          <main>{children}</main>
        ) : (
          <AdminLayout>
            <main>{children}</main>
          </AdminLayout>
        )
        }
      </body>
    </html>
  );
}
